CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    status_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    deleted TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_project_status
        FOREIGN KEY (status_id)
        REFERENCES project_status(id)
        DEFERRABLE INITIALLY DEFERRED
);