CREATE TABLE project_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    deleted TIMESTAMP WITH TIME ZONE
);

-- Insertar los valores iniciales
INSERT INTO project_status (name) VALUES
('pendiente'),
('en progreso'),
('aprobado'),
('cancelado');