create table public.users (
  id bigint generated by default as identity not null,
  name text not null,
  paternal_surname text not null,
  maternal_surname text null,
  email text not null,
  hashed_password text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  deleted timestamp with time zone null,
  constraint users_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_users_email on public.users using btree (email) TABLESPACE pg_default;

create index IF not exists idx_users_deleted on public.users using btree (deleted) TABLESPACE pg_default
where
  (deleted is null);

create unique INDEX IF not exists unique_active_email on public.users using btree (email) TABLESPACE pg_default
where
  (deleted is null);